Приветствую, Анатолий!
В задаче 1 вроде сделал всё, даже двумя вариантами. Первый мне показался предпочтительнее.
Второй (закомментированный) сделал первым по времени, решил оставить тоже.

В 3 задаче с выводом нескольких аргументов через запятую справился.
НО, Traceback ругается, на то что ждёт только 1 позиционный аргумент. Это доделанная или нет часть работы?
А вот с именованными аргументами не получилось.

4 задачка, тут вроде всё ок. Верные значения считает, не верные выкидывает ошибку ValueError: wrong value.